const INITIAL_pmp_KNOWLEDGE_BASE =
{
  "topics": [
    { "id": "planned_value_pv", "title": "Planned Value (PV)", "category": "Earned Value Management", "description": "Planned % Complete × BAC. It represents what should have been done at a given point in time." },
    { "id": "earned_value_ev", "title": "Earned Value (EV)", "category": "Earned Value Management", "description": "Actual % Complete × BAC. It measures the work actually completed expressed in terms of the authorized budget." },
    { "id": "actual_cost_ac", "title": "Actual Cost (AC)", "category": "Earned Value Management", "description": "Total actual cost incurred for work performed on an activity during a specific period." },
    { "id": "cost_variance_cv", "title": "Cost Variance (CV)", "category": "Earned Value Management", "description": "EV - AC. A measure of cost performance on a project." },
    { "id": "schedule_variance_sv", "title": "Schedule Variance (SV)", "category": "Earned Value Management", "description": "EV - PV. A measure of schedule performance on a project." },
    { "id": "cost_performance_index_cpi", "title": "Cost Performance Index (CPI)", "category": "Earned Value Management", "description": "EV / AC. A measure of the cost efficiency of budgeted resources." },
    { "id": "schedule_performance_index_spi", "title": "Schedule Performance Index (SPI)", "category": "Earned Value Management", "description": "EV / PV. A measure of schedule efficiency." },
    { "id": "estimate_at_completion_eac", "title": "Estimate at Completion (EAC)", "category": "Earned Value Management", "description": "BAC / CPI. A forecast of the expected total cost of completing all work." },
    { "id": "estimate_to_complete_etc", "title": "Estimate to Complete (ETC)", "category": "Earned Value Management", "description": "EAC - AC. The expected cost to finish all remaining project work." },
    { "id": "variance_at_completion_vac", "title": "Variance at Completion (VAC)", "category": "Earned Value Management", "description": "BAC - EAC. A projection of the budget deficit or surplus." },
    { "id": "tcpi_formula", "title": "To-Complete Performance Index (TCPI)", "category": "Earned Value Management", "description": "Ratio of cost to finish outstanding work to the remaining budget." },
    { "id": "communication_channels_formula", "title": "Communication Channels Formula", "category": "Communication", "description": "n(n - 1) / 2. Used to calculate the number of potential communication paths." },
    { "id": "risk_exposure_formula", "title": "Risk Exposure", "category": "Risk Management", "description": "Probability × Impact. Helps quantify the significance of a risk." },
    { "id": "expected_monetary_value_emv", "title": "Expected Monetary Value (EMV)", "category": "Risk Management", "description": "Probability × Impact. Estimated value of an outcome in monetary terms." },
    { "id": "triangular_estimate", "title": "Triangular Estimate", "category": "Estimating", "description": "(Optimistic + Most Likely + Pessimistic) / 3." },
    { "id": "pert_estimate", "title": "PERT Estimate", "category": "Estimating", "description": "(Optimistic + 4 × Most Likely + Pessimistic) / 6." },
    { "id": "standard_deviation_formula", "title": "Standard Deviation", "category": "Estimating", "description": "(Pessimistic - Optimistic) / 6." },
    { "id": "resource_utilization_formula", "title": "Resource Utilization", "category": "Resource Management", "description": "Actual Time Worked / Available Time." },
    { "id": "float_slack_calc", "title": "Float (Slack)", "category": "Critical Path Method", "description": "Late Start - Early Start OR Late Finish - Early Finish." },
    { "id": "stewardship", "title": "Stewardship", "category": "Project Management Principles", "description": "Being a diligent, respectful, and caring steward of project resources." },
    { "id": "team_principle", "title": "Team", "category": "Project Management Principles", "description": "Creating a collaborative project team environment." },
    { "id": "stakeholders_principle", "title": "Stakeholders", "category": "Project Management Principles", "description": "Effectively engaging with stakeholders throughout the project." },
    { "id": "value_focus", "title": "Value", "category": "Project Management Principles", "description": "Continually evaluating and focusing on the delivery of project value." },
    { "id": "systems_thinking", "title": "Systems Thinking", "category": "Project Management Principles", "description": "Recognizing, evaluating, and responding to system interactions." },
    { "id": "leadership_behaviors_principle", "title": "Leadership Behaviors", "category": "Project Management Principles", "description": "Demonstrating leadership through influence, motivation, and empathy." },
    { "id": "tailoring_principle", "title": "Tailoring", "category": "Project Management Principles", "description": "Adapting the approach based on project context and objectives." },
    { "id": "quality_focus", "title": "Quality", "category": "Project Management Principles", "description": "Building quality into both project processes and deliverables." },
    { "id": "navigate_complexity_principle", "title": "Complexity", "category": "Project Management Principles", "description": "Continually navigating project complexity resulting from behavior and systems." },
    { "id": "optimize_risk_responses_principle", "title": "Risk", "category": "Project Management Principles", "description": "Optimizing responses to both threats and opportunities." },
    { "id": "adaptability_resiliency_principle", "title": "Adaptability and Resiliency", "category": "Project Management Principles", "description": "Building the capacity to advance work despite change or setbacks." },
    { "id": "enable_change_principle", "title": "Change", "category": "Project Management Principles", "description": "Enabling transitions from current to future states." },
    { "id": "stakeholders_domain", "title": "Stakeholders Domain", "category": "Performance Domains", "description": "Performance domain addressing activities and functions associated with stakeholders." },
    { "id": "team_domain", "title": "Team Domain", "category": "Performance Domains", "description": "Performance domain addressing activities associated with people producing deliverables." },
    { "id": "dev_approach_lifecycle_domain", "title": "Development Approach Domain", "category": "Performance Domains", "description": "Domain addressing delivery cadence and life cycle phases." },
    { "id": "planning_domain", "title": "Planning Domain", "category": "Performance Domains", "description": "Domain addressing the coordination of work for deliverables." },
    { "id": "project_work_domain", "title": "Project Work Domain", "category": "Performance Domains", "description": "Domain associated with performing the work to enable team delivery." },
    { "id": "delivery_domain", "title": "Delivery Domain", "category": "Performance Domains", "description": "Domain addressing scope and quality expectations for deliverables." },
    { "id": "measurement_domain", "title": "Measurement Domain", "category": "Performance Domains", "description": "Domain assessing project status and taking corrective actions." },
    { "id": "uncertainty_domain", "title": "Uncertainty Domain", "category": "Performance Domains", "description": "Domain addressing risk and unpredictability." },
    { "id": "people_domain_eco", "title": "People Domain (ECO)", "category": "PMP Exam Domains", "description": "Focuses on leading teams and managing conflict (42% of exam)." },
    { "id": "process_domain_eco", "title": "Process Domain (ECO)", "category": "PMP Exam Domains", "description": "Covers technical aspects like planning, risk, and WBS (50% of exam)." },
    { "id": "business_environment_domain_eco", "title": "Business Environment Domain (ECO)", "category": "PMP Exam Domains", "description": "Connects projects to strategy and compliance (8% of exam)." },
    { "id": "critical_path", "title": "Critical Path", "category": "Critical Path Method", "description": "The sequence of activities representing the longest path through a project." },
    { "id": "forward_pass", "title": "Forward Pass", "category": "Critical Path Method", "description": "Calculating Early Start and Early Finish for all activity sequences." },
    { "id": "backward_pass", "title": "Backward Pass", "category": "Critical Path Method", "description": "Calculating Late Start and Late Finish for all activity sequences." },
    { "id": "total_float", "title": "Total Float", "category": "Critical Path Method", "description": "Time a task can be delayed without delaying the overall project." },
    { "id": "free_float", "title": "Free Float", "category": "Critical Path Method", "description": "Time a task can be delayed without delaying subsequent dependent tasks." },
    { "id": "crashing_method", "title": "Crashing", "category": "Schedule Compression", "description": "Shortening duration for least incremental cost by adding resources." },
    { "id": "fast_tracking_method", "title": "Fast Tracking", "category": "Schedule Compression", "description": "Performing sequential activities in parallel to reduce time." },
    { "id": "earliest_start", "title": "Earliest Start (ES)", "category": "Critical Path Method", "description": "The earliest time an activity can begin." },
    { "id": "earliest_finish", "title": "Earliest Finish (EF)", "category": "Critical Path Method", "description": "The earliest time an activity can end (ES + Duration)." },
    { "id": "latest_start", "title": "Latest Start (LS)", "category": "Critical Path Method", "description": "The latest an activity can start without delaying the project." },
    { "id": "latest_finish", "title": "Latest Finish (LF)", "category": "Critical Path Method", "description": "The latest an activity can finish without delaying the project." },
    { "id": "responsibility_ethics", "title": "Responsibility", "category": "Ethics", "description": "Taking ownership for decisions and acting in the best interest of the project." },
    { "id": "respect_ethics", "title": "Respect", "category": "Ethics", "description": "Appropriate treatment of people and resources, and handling conflict directly." },
    { "id": "fairness_ethics", "title": "Fairness", "category": "Ethics", "description": "Making impartial decisions without favoritism, prejudice, or bribery." },
    { "id": "honesty_ethics", "title": "Honesty", "category": "Ethics", "description": "Truthful communication and creating an environment where others tell the truth." },
    { "id": "situational_leadership_ii", "title": "Situational Leadership II", "category": "Models", "description": "Measures development using competence and commitment." },
    { "id": "oscar_model", "title": "OSCAR Model", "category": "Models", "description": "Coaching model: Outcome, Situation, Choices, Actions, Review." },
    { "id": "cross_cultural_communication", "title": "Cross-Cultural Communication", "category": "Models", "description": "Transmission influenced by sender/receiver experience and language." },
    { "id": "effectiveness_comm_channels", "title": "Effectiveness of Communication Channels", "category": "Models", "description": "Axes of effectiveness and richness (face-to-face is richest)." },
    { "id": "gulf_execution_evaluation", "title": "Gulf of Execution and Evaluation", "category": "Models", "description": "Difference between user intention and system capability." },
    { "id": "hygiene_motivational_factors", "title": "Hygiene and Motivational Factors", "category": "Models", "description": "Herzberg's theory on job satisfaction vs dissatisfaction." },
    { "id": "intrinsic_extrinsic_motivation", "title": "Intrinsic vs Extrinsic Motivation", "category": "Models", "description": "Pink's theory on Autonomy, Mastery, and Purpose." },
    { "id": "theory_needs", "title": "Theory of Needs", "category": "Models", "description": "McClelland's drivers: Achievement, Power, and Affiliation." },
    { "id": "theory_x_y_z", "title": "Theory X, Theory Y, and Theory Z", "category": "Models", "description": "Spectrum of management styles based on employee motivation." },
    { "id": "managing_change_organizations", "title": "Managing Change in Organizations", "category": "Models", "description": "Iterative framework: Formulate, Plan, Implement, Manage, Sustain." },
    { "id": "adkar_model", "title": "ADKAR Model", "category": "Models", "description": "Steps: Awareness, Desire, Knowledge, Ability, Reinforcement." },
    { "id": "8_step_process_change", "title": "8-Step Process for Leading Change", "category": "Models", "description": "Kotter's top-down approach for organizational transformation." },
    { "id": "virginia_satir_model", "title": "Virginia Satir Change Model", "category": "Models", "description": "Stages of coping: Status Quo, Chaos, Transforming Idea, Practice." },
    { "id": "transition_model", "title": "Transition Model", "category": "Models", "description": "Psychological stages: Ending, Neutral Zone, New Beginning." },
    { "id": "cynefin_framework", "title": "Cynefin Framework", "category": "Models", "description": "Diagnosing obvious, complicated, complex, and chaotic contexts." },
    { "id": "stacey_matrix", "title": "Stacey Matrix", "category": "Models", "description": "Determines complexity based on requirements and tech uncertainty." },
    { "id": "tuckman_ladder", "title": "Tuckman Ladder", "category": "Models", "description": "Stages: Forming, Storming, Norming, Performing, Adjourning." },
    { "id": "drexler_sibbet_model", "title": "Drexler/Sibbet Team Performance", "category": "Models", "description": "Seven steps from orientation to renewal." },
    { "id": "conflict_model", "title": "Conflict Model", "category": "Models", "description": "Styles: Confronting, Collaborating, Compromising, Smoothing, Forcing, Avoiding." },
    { "id": "negotiation_win_win", "title": "Negotiation (Win-Win)", "category": "Models", "description": "Outcome where all parties are satisfied." },
    { "id": "process_groups_model", "title": "Process Groups", "category": "Models", "description": "Organizing structure: Initiating, Planning, Executing, M&C, Closing." },
    { "id": "salience_model", "title": "Salience Model", "category": "Models", "description": "Stakeholder identification by power, legitimacy, and urgency." },
    { "id": "alternatives_analysis", "title": "Alternatives Analysis", "category": "Methods", "description": "Evaluating identified options to select the best approach." },
    { "id": "assumption_constraint_analysis", "title": "Assumption and Constraint Analysis", "category": "Methods", "description": "Ensuring assumptions and constraints are integrated into plans." },
    { "id": "benchmarking", "title": "Benchmarking", "category": "Methods", "description": "Comparing practices to other organizations to find best practices." },
    { "id": "payback_period", "title": "Payback Period", "category": "Methods", "description": "Time needed to recover an investment." },
    { "id": "irr_def", "title": "Internal Rate of Return (IRR)", "category": "Methods", "description": "Projected annual yield of a project investment." },
    { "id": "roi_def", "title": "Return on Investment (ROI)", "category": "Methods", "description": "Percent financial return compared to initial cost." },
    { "id": "npv_def", "title": "Net Present Value (NPV)", "category": "Methods", "description": "Future value of expected benefits in today's terms." },
    { "id": "cost_benefit_analysis", "title": "Cost-Benefit Analysis", "category": "Methods", "description": "Financial tool used to determine benefits against costs." },
    { "id": "check_sheet", "title": "Check Sheet", "category": "Methods", "description": "Tally sheet used to collect and segregate data." },
    { "id": "decision_tree_analysis", "title": "Decision Tree Analysis", "category": "Methods", "description": "Evaluating chains of options in the presence of uncertainty." },
    { "id": "earned_value_analysis", "title": "Earned Value Analysis", "category": "Methods", "description": "Utilizing scope, schedule, and cost measures for performance." },
    { "id": "influence_diagram", "title": "Influence Diagram", "category": "Methods", "description": "Graphical representation of causal influences and outcomes." },
    { "id": "life_cycle_assessment", "title": "Life Cycle Assessment", "category": "Methods", "description": "Tool used to evaluate total environmental impact." },
    { "id": "make_or_buy_analysis", "title": "Make-or-Buy Analysis", "category": "Methods", "description": "Choosing between internal manufacture and external purchase." },
    { "id": "probability_impact_matrix", "title": "Probability and Impact Matrix", "category": "Methods", "description": "Grid mapping each risk for prioritization." },
    { "id": "process_analysis", "title": "Process Analysis", "category": "Methods", "description": "Systematic review of steps to perform an activity." },
    { "id": "regression_analysis", "title": "Regression Analysis", "category": "Methods", "description": "Statistical relationship to infer future performance." },
    { "id": "reserve_analysis", "title": "Reserve Analysis", "category": "Methods", "description": "Evaluating schedule and budget reserve sufficiency." },
    { "id": "root_cause_analysis", "title": "Root Cause Analysis", "category": "Methods", "description": "Determining basic underlying reasons for variance." },
    { "id": "sensitivity_analysis", "title": "Sensitivity Analysis", "category": "Methods", "description": "Determining which risks have the most potential impact." },
    { "id": "monte_carlo_simulation", "title": "Monte Carlo Simulation", "category": "Methods", "description": "Iterations of a model to develop a probability distribution." },
    { "id": "stakeholder_analysis", "title": "Stakeholder Analysis", "category": "Methods", "description": "Gathering info to determine whose interests to account for." },
    { "id": "swot_analysis", "title": "SWOT Analysis", "category": "Methods", "description": "Assessing strengths, weaknesses, opportunities, and threats." },
    { "id": "trend_analysis", "title": "Trend Analysis", "category": "Methods", "description": "Mathematical models forecasting based on historical results." },
    { "id": "value_stream_mapping", "title": "Value Stream Mapping", "category": "Methods", "description": "Lean method used to document and improve information flow." },
    { "id": "variance_analysis", "title": "Variance Analysis", "category": "Methods", "description": "Determining cause and degree of difference from baseline." },
    { "id": "what_if_scenario_analysis", "title": "What-If Scenario Analysis", "category": "Methods", "description": "Evaluating scenarios to predict effects on objectives." },
    { "id": "affinity_grouping", "title": "Affinity Grouping", "category": "Methods", "description": "Classifying items by likeness (e.g., T-shirt sizing)." },
    { "id": "analogous_estimating", "title": "Analogous Estimating", "category": "Methods", "description": "Using historical data from similar projects to estimate." },
    { "id": "function_point", "title": "Function Point", "category": "Methods", "description": "Estimate of business functionality in an info system." },
    { "id": "parametric_estimating", "title": "Parametric Estimating", "category": "Methods", "description": "Algorithm used based on historical data and parameters." },
    { "id": "relative_estimating", "title": "Relative Estimating", "category": "Methods", "description": "Comparison against similar bodies of work." },
    { "id": "single_point_estimating", "title": "Single-Point Estimating", "category": "Methods", "description": "Best-guess estimate calculated from data." },
    { "id": "story_point_estimating", "title": "Story Point Estimating", "category": "Methods", "description": "Assigning abstract points of effort to user stories." },
    { "id": "wideband_delphi", "title": "Wideband Delphi", "category": "Methods", "description": "Subject experts reaching consensus through multiple rounds." },
    { "id": "backlog_refinement", "title": "Backlog Refinement", "category": "Methods", "description": "Elaborating and reprioritizing work for upcoming iterations." },
    { "id": "bidder_conference", "title": "Bidder Conference", "category": "Methods", "description": "Meetings with prospective sellers to ensure common understanding." },
    { "id": "change_control_board_mtg", "title": "Change Control Board Meeting", "category": "Methods", "description": "Accountable group reviewing and approving changes." },
    { "id": "daily_standup", "title": "Daily Standup", "category": "Methods", "description": "Brief collaboration to review progress and obstacles." },
    { "id": "iteration_planning", "title": "Iteration Planning", "category": "Methods", "description": "Clarifying backlog details and effort for a timebox." },
    { "id": "iteration_review", "title": "Iteration Review", "category": "Methods", "description": "Demonstrating accomplished work at iteration end." },
    { "id": "kickoff_meeting", "title": "Kickoff Meeting", "category": "Methods", "description": "Gathering stakeholders to set expectations and start work." },
    { "id": "lessons_learned_meeting", "title": "Lessons Learned Meeting", "category": "Methods", "description": "Sharing knowledge to improve future performance." },
    { "id": "planning_meeting", "title": "Planning Meeting", "category": "Methods", "description": "Creating and reviewing plans to secure commitment." },
    { "id": "project_closeout", "title": "Project Closeout Meeting", "category": "Methods", "description": "Obtaining final acceptance of delivered scope." },
    { "id": "project_review", "title": "Project Review Meeting", "category": "Methods", "description": "Assessing status and evaluating value at phase end." },
    { "id": "release_planning_mtg", "title": "Release Planning", "category": "Methods", "description": "Identifying high-level plans for releasing value." },
    { "id": "retrospective", "title": "Retrospective", "category": "Methods", "description": "Regular workshop to improve both process and product." },
    { "id": "risk_review", "title": "Risk Review", "category": "Methods", "description": "Analyzing status of existing risks and identifying new ones." },
    { "id": "status_meeting", "title": "Status Meeting", "category": "Methods", "description": "Scheduled event to exchange info on current progress." },
    { "id": "steering_committee", "title": "Steering Committee", "category": "Methods", "description": "Senior stakeholders provide project direction." },
    { "id": "impact_mapping", "title": "Impact Mapping", "category": "Methods", "description": "Strategic visual roadmap for product development." },
    { "id": "prioritization_schema", "title": "Prioritization Schema", "category": "Methods", "description": "Methods to prioritize features or risks (e.g., MoSCoW)." },
    { "id": "timebox", "title": "Timebox", "category": "Methods", "description": "Short, fixed period in which work is completed." },
    { "id": "business_case_artifact", "title": "Business Case", "category": "Artifacts", "description": "Value proposition justifying the proposed project." },
    { "id": "business_model_canvas", "title": "Business Model Canvas", "category": "Artifacts", "description": "One-page visual summary of value and customers." },
    { "id": "project_brief", "title": "Project Brief", "category": "Artifacts", "description": "High-level overview of goals and processes." },
    { "id": "project_charter_artifact", "title": "Project Charter", "category": "Artifacts", "description": "Document issued by initiator authorizing project existence." },
    { "id": "project_vision_statement", "title": "Project Vision Statement", "category": "Artifacts", "description": "Concise description stating purpose and inspiration." },
    { "id": "roadmap_artifact", "title": "Roadmap", "category": "Artifacts", "description": "High-level timeline depicting milestones and decision points." },
    { "id": "assumption_log", "title": "Assumption Log", "category": "Artifacts", "description": "Record of all assumptions and constraints." },
    { "id": "backlog_artifact", "title": "Backlog", "category": "Artifacts", "description": "Ordered list of prioritized work to be done." },
    { "id": "change_log_artifact", "title": "Change Log", "category": "Artifacts", "description": "Comprehensive list of changes submitted during a project." },
    { "id": "issue_log_artifact", "title": "Issue Log", "category": "Artifacts", "description": "Used to record and monitor active issues." },
    { "id": "lessons_learned_register", "title": "Lessons Learned Register", "category": "Artifacts", "description": "Repository for knowledge gained during a project." },
    { "id": "risk_adjusted_backlog", "title": "Risk-Adjusted Backlog", "category": "Artifacts", "description": "Backlog including actions to address threats/opportunities." },
    { "id": "risk_register_artifact", "title": "Risk Register", "category": "Artifacts", "description": "Repository for recorded individual project risks." },
    { "id": "stakeholder_register_artifact", "title": "Stakeholder Register", "category": "Artifacts", "description": "Record of project stakeholders and classification." },
    { "id": "change_control_plan", "title": "Change Control Plan", "category": "Artifacts", "description": "Describes how change control will be implemented." },
    { "id": "communications_mgmt_plan", "title": "Communications Management Plan", "category": "Artifacts", "description": "Describes how info will be administered." },
    { "id": "cost_management_plan", "title": "Cost Management Plan", "category": "Artifacts", "description": "Describes how costs will be planned and controlled." },
    { "id": "iteration_plan", "title": "Iteration Plan", "category": "Artifacts", "description": "Detailed plan for the current iteration." },
    { "id": "procurement_mgmt_plan", "title": "Procurement Management Plan", "category": "Artifacts", "description": "Describes acquisition of goods from outside the org." },
    { "id": "project_management_plan", "title": "Project Management Plan", "category": "Artifacts", "description": "Describes execution, monitoring, and closing." },
    { "id": "quality_mgmt_plan", "title": "Quality Management Plan", "category": "Artifacts", "description": "Describes implementation of quality policies." },
    { "id": "release_plan_artifact", "title": "Release Plan", "category": "Artifacts", "description": "Expectations for features over multiple iterations." },
    { "id": "requirements_mgmt_plan", "title": "Requirements Management Plan", "category": "Artifacts", "description": "Describes analysis and management of needs." },
    { "id": "resource_mgmt_plan", "title": "Resource Management Plan", "category": "Artifacts", "description": "Acquisition and allocation of project resources." },
    { "id": "risk_management_plan", "title": "Risk Management Plan", "category": "Artifacts", "description": "Structure for risk management activities." },
    { "id": "scope_management_plan", "title": "Scope Management Plan", "category": "Artifacts", "description": "Defining, developed, and validating project scope." },
    { "id": "schedule_mgmt_plan", "title": "Schedule Management Plan", "category": "Artifacts", "description": "Criteria for developing and controlling the schedule." },
    { "id": "stakeholder_engagement_plan", "title": "Stakeholder Engagement Plan", "category": "Artifacts", "description": "Promotes productive stakeholder involvement." },
    { "id": "test_plan_artifact", "title": "Test Plan", "category": "Artifacts", "description": "Describes deliverables tested and the process." },
    { "id": "obs_hierarchy", "title": "Organizational Breakdown Structure (OBS)", "category": "Artifacts", "description": "Hierarchy illustrating activities to organizational units." },
    { "id": "pbs_hierarchy", "title": "Product Breakdown Structure", "category": "Artifacts", "description": "Hierarchy structure of a product's components." },
    { "id": "resource_breakdown_structure", "title": "Resource Breakdown Structure", "category": "Artifacts", "description": "Hierarchy representation of resources by type." },
    { "id": "rbs_hierarchy", "title": "Risk Breakdown Structure (RBS)", "category": "Artifacts", "description": "Hierarchy representation of potential risk sources." },
    { "id": "wbs_artifact", "title": "Work Breakdown Structure (WBS)", "category": "Artifacts", "description": "Decomposition of total scope to be carried out." },
    { "id": "milestone_schedule_artifact", "title": "Milestone Schedule", "category": "Artifacts", "description": "Presents milestones with planned dates." },
    { "id": "pmb_artifact", "title": "Performance Measurement Baseline (PMB)", "category": "Artifacts", "description": "Integrated scope, schedule, and cost baselines." },
    { "id": "project_schedule_artifact", "title": "Project Schedule", "category": "Artifacts", "description": "Linked activities with dates, durations, and resources." },
    { "id": "scope_baseline_artifact", "title": "Scope Baseline", "category": "Artifacts", "description": "Scope statement, WBS, and WBS dictionary." },
    { "id": "affinity_diagram", "title": "Affinity Diagram", "category": "Artifacts", "description": "Ideas classified into groups for review." },
    { "id": "burn_chart_visual", "title": "Burn Chart", "category": "Artifacts", "description": "Visual of work remaining vs completed." },
    { "id": "cause_and_effect_visual", "title": "Cause-and-Effect Diagram", "category": "Artifacts", "description": "Visualizing undesirable effects back to root causes." },
    { "id": "cfd_visual", "title": "Cumulative Flow Diagram (CFD)", "category": "Artifacts", "description": "Indicates features completed over time." },
    { "id": "cycle_time_chart", "title": "Cycle Time Chart", "category": "Artifacts", "description": "Visual average task completion time." },
    { "id": "dashboard_visual", "title": "Dashboard", "category": "Artifacts", "description": "Set of charts depicting project progress." },
    { "id": "flowchart_visual", "title": "Flowchart", "category": "Artifacts", "description": "Depiction of inputs and outputs of processes." },
    { "id": "gantt_chart_visual", "title": "Gantt Chart", "category": "Artifacts", "description": "Bar chart showing activity durations and dates." },
    { "id": "histogram_visual", "title": "Histogram", "category": "Artifacts", "description": "Bar chart representation of numerical data." },
    { "id": "info_radiator_artifact", "title": "Information Radiator", "category": "Artifacts", "description": "Physical displays enabling knowledge sharing." },
    { "id": "lead_time_chart_visual", "title": "Lead Time Chart", "category": "Artifacts", "description": "Trend of average item completion time." },
    { "id": "prioritization_matrix_visual", "title": "Prioritization Matrix", "category": "Artifacts", "description": "Scatter diagram plotting effort vs value." },
    { "id": "net_diagram_visual", "title": "Project Schedule Network Diagram", "category": "Artifacts", "description": "Logical relationships among schedule activities." },
    { "id": "traceability_matrix_visual", "title": "Requirements Traceability Matrix", "category": "Artifacts", "description": "Links requirements to satisfaction deliverables." },
    { "id": "ram_raci_visual", "title": "Responsibility Assignment Matrix (RAM)", "category": "Artifacts", "description": "Grid showing resources assigned to work packages." },
    { "id": "scatter_diagram_visual", "title": "Scatter Diagram", "category": "Artifacts", "description": "Graph showing relationship between two variables." },
    { "id": "s_curve_visual", "title": "S-Curve", "category": "Artifacts", "description": "Displays cumulative costs over a period." },
    { "id": "engagement_matrix_visual", "title": "Stakeholder Engagement Matrix", "category": "Artifacts", "description": "Compares current vs desired engagement levels." },
    { "id": "story_map_visual", "title": "Story Map", "category": "Artifacts", "description": "Model of desired product features." },
    { "id": "throughput_chart_visual", "title": "Throughput Chart", "category": "Artifacts", "description": "Diagram of accepted deliverables over time." },
    { "id": "use_case_artifact", "title": "Use Case", "category": "Artifacts", "description": "Explores user interaction with a system." },
    { "id": "velocity_chart_visual", "title": "Velocity Chart", "category": "Artifacts", "description": "Tracks team productivity rate per interval." },
    { "id": "quality_report_artifact", "title": "Quality Report", "category": "Artifacts", "description": "Summary of findings from quality control." },
    { "id": "risk_report_artifact", "title": "Risk Report", "category": "Artifacts", "description": "Progressive summary on individual and overall risk." },
    { "id": "status_report_artifact", "title": "Status Report", "category": "Artifacts", "description": "Report on progress and performance forecasts." },
    { "id": "fixed_price_contract", "title": "Fixed-Price Contract", "category": "Contracts", "description": "Agreement setting fixed fee regardless of cost." },
    { "id": "cost_reimbursable_contract", "title": "Cost-Reimbursable Contract", "category": "Contracts", "description": "Payment for actual costs plus seller fee." },
    { "id": "t_m_contract", "title": "Time and Materials (T&M)", "category": "Contracts", "description": "Hybrid arrangement containing both FP and CR aspects." },
    { "id": "idiq_contract", "title": "Indefinite Delivery Indefinite Quantity (IDIQ)", "category": "Contracts", "description": "Contract for indefinite quantity within fixed time." },
    { "id": "activity_list_artifact", "title": "Activity List", "category": "Artifacts", "description": "Tabulation of scheduled activities." },
    { "id": "bid_docs_artifact", "title": "Bid Documents", "category": "Artifacts", "description": "Used to request proposals from prospective sellers." },
    { "id": "metrics_definition", "title": "Metrics", "category": "Artifacts", "description": "Description of project attribute and how to measure." },
    { "id": "project_calendar", "title": "Project Calendar", "category": "Artifacts", "description": "Identifies available working days and shifts." },
    { "id": "requirements_docs", "title": "Requirements Documentation", "category": "Artifacts", "description": "Record of product requirements and related info." },
    { "id": "team_charter_artifact", "title": "Project Team Charter", "category": "Artifacts", "description": "Records team values and operating guidelines." },
    { "id": "user_story_artifact", "title": "User Story", "category": "Artifacts", "description": "Brief outcome description for a specific user." },
    { "id": "portfolio_def", "title": "Portfolio", "category": "Fundamentals", "description": "Projects and programs managed as a group for strategy." },
    { "id": "program_def", "title": "Program", "category": "Fundamentals", "description": "Related projects managed to obtain specific benefits." },
    { "id": "project_def", "title": "Project", "category": "Fundamentals", "description": "Temporary endeavor creating a unique result." },
    { "id": "outcome_def", "title": "Outcome", "category": "Fundamentals", "description": "End result or consequence of a process or project." },
    { "id": "value_def", "title": "Value", "category": "Fundamentals", "description": "The worth, importance, or usefulness of something." },
    { "id": "servant_leadership", "title": "Servant Leadership", "category": "Leadership", "description": "Leading by focusing on team needs and self-organization." },
    { "id": "emotional_intelligence_def", "title": "Emotional Intelligence", "category": "Leadership", "description": "Ability to manage personal and group emotions." },
    { "id": "triple_bottom_line", "title": "Triple Bottom Line", "category": "Planning", "description": "Evaluating profit, people, and the planet." },
    { "id": "scope_creep_def", "title": "Scope Creep", "category": "Delivery", "description": "Uncontrolled expansion of project scope." },
    { "id": "databricks_history", "title": "Azure Databricks History", "category": "Corporate History", "description": "Integrated into Microsoft as first-party service in 2017." },
    { "id": "lakehouse_arch", "title": "Lakehouse Architecture", "category": "Architecture Patterns", "description": "Unifies warehouse performance with low-cost lake storage." }
  ],
  "edges": [
    { "from": "pv", "to": "sv", "label": "used in schedule variance calculation" },
    { "from": "ev", "to": "sv", "label": "used in schedule variance calculation" },
    { "from": "ev", "to": "cv", "label": "used in cost variance calculation" },
    { "from": "ac", "to": "cv", "label": "used in cost variance calculation" },
    { "from": "ev", "to": "cpi", "label": "used in cost performance index calculation" },
    { "from": "ac", "to": "cpi", "label": "used in cost performance index calculation" },
    { "from": "ev", "to": "spi", "label": "used in schedule performance index calculation" },
    { "from": "pv", "to": "spi", "label": "used in schedule performance index calculation" },
    { "from": "cpi", "to": "eac", "label": "influences forecast of final cost" },
    { "from": "eac", "to": "etc", "label": "used to determine cost to complete work" },
    { "from": "ac", "to": "etc", "label": "used to determine cost to complete work" },
    { "from": "bac", "to": "vac", "label": "used in variance at completion calculation" },
    { "from": "eac", "to": "vac", "label": "used in variance at completion calculation" },
    { "from": "risk_exposure_formula", "to": "emv", "label": "provides calculation basis for" },
    { "from": "stewardship", "to": "people_domain_eco", "label": "guides behavior within" },
    { "from": "team_principle", "to": "team_domain", "label": "guides behavior for" },
    { "from": "stakeholders_principle", "to": "stakeholders_domain", "label": "guides engagement with" },
    { "from": "value_focus", "to": "delivery_domain", "label": "emphasizes outcomes for" },
    { "from": "systems_thinking", "to": "navigate_complexity_principle", "label": "supports identifying issues in" },
    { "from": "leadership_behaviors_principle", "to": "team_domain", "label": "shapes the culture of" },
    { "from": "tailoring_principle", "to": "planning_domain", "label": "adapts methods for" },
    { "from": "quality_focus", "to": "delivery_domain", "label": "ensures conformance within" },
    { "from": "navigate_complexity_principle", "to": "uncertainty_domain", "label": "manages ambiguity in" },
    { "from": "optimize_risk_responses_principle", "to": "uncertainty_domain", "label": "provides strategies for" },
    { "from": "adaptability_resiliency_principle", "to": "project_work_domain", "label": "allows for adjustment in" },
    { "from": "enable_change_principle", "to": "business_environment_domain_eco", "label": "aligns with strategy in" },
    { "from": "critical_path", "to": "total_duration", "label": "defines the minimum duration" },
    { "from": "float_slack_calc", "to": "critical_path", "label": "is zero on the" },
    { "from": "forward_pass", "to": "earliest_start", "label": "calculates the" },
    { "from": "backward_pass", "to": "latest_start", "label": "calculates the" },
    { "from": "crashing_method", "to": "project_work_domain", "label": "technique used in" },
    { "from": "fast_tracking_method", "to": "planning_domain", "label": "technique used in" },
    { "from": "responsibility_ethics", "to": "process_domain_eco", "label": "underpins performance in" },
    { "from": "tuckman_ladder", "to": "team_domain", "label": "describes development stages of" },
    { "from": "conflict_model", "to": "people_domain_eco", "label": "key for managing disagreements in" },
    { "from": "npv_def", "to": "business_case_artifact", "label": "serves as justification for" },
    { "from": "wbs_artifact", "to": "scope_baseline_artifact", "label": "component of" },
    { "from": "burn_chart_visual", "to": "measurement_domain", "label": "visualizes progress in" },
    { "from": "stakeholder_register_artifact", "to": "stakeholders_domain", "label": "records individuals in" },
    { "from": "risk_register_artifact", "to": "uncertainty_domain", "label": "tracks factors in" },
    { "from": "delta_lake_log", "to": "lakehouse_arch", "label": "enables foundation of" }
  ]
};